version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - deploy:
          name: digital-ocean
          command: ssh -o "StrictHostKeyChecking no" root@46.101.120.105 "cd ~/circleciexpress; git pull; npm install; npm start &"
workflows:
    build-and-test:
      jobs:
        - build-and-test
  